# AUTO-GENERATED by scripts/gen_error_codes.py from eyerate's
# error-codes.yaml. DO NOT EDIT — regenerate from the YAML source.
"""Typed error-code constants for eyerate (EYERATE)."""

COMPONENT = 'EYERATE'
SUPPORTED_LOCALES = ['en', 'es']

EYERATE_PROV_001 = 'EYERATE-PROV-001'
EYERATE_PROV_002 = 'EYERATE-PROV-002'
EYERATE_PROV_003 = 'EYERATE-PROV-003'
EYERATE_PROV_004 = 'EYERATE-PROV-004'
EYERATE_API_001 = 'EYERATE-API-001'
EYERATE_API_002 = 'EYERATE-API-002'
EYERATE_API_003 = 'EYERATE-API-003'
EYERATE_API_004 = 'EYERATE-API-004'
EYERATE_API_005 = 'EYERATE-API-005'

ALL_CODES = frozenset({
    'EYERATE-PROV-001',
    'EYERATE-PROV-002',
    'EYERATE-PROV-003',
    'EYERATE-PROV-004',
    'EYERATE-API-001',
    'EYERATE-API-002',
    'EYERATE-API-003',
    'EYERATE-API-004',
    'EYERATE-API-005',
})

CODE_METADATA = {
    'EYERATE-PROV-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'PROV'},
    'EYERATE-PROV-002': {'severity': 'warning', 'log_route': 'n/a', 'facility': 'PROV'},
    'EYERATE-PROV-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'PROV'},
    'EYERATE-PROV-004': {'severity': 'error', 'log_route': 'aggregate', 'facility': 'PROV'},
    'EYERATE-API-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'API'},
    'EYERATE-API-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'API'},
    'EYERATE-API-003': {'severity': 'warning', 'log_route': 'n/a', 'facility': 'API'},
    'EYERATE-API-004': {'severity': 'warning', 'log_route': 'n/a', 'facility': 'API'},
    'EYERATE-API-005': {'severity': 'warning', 'log_route': 'n/a', 'facility': 'API'},
}
